/**
 * @file cordic.c
 * @author simakeng (simakeng@outlook.com)
 * @brief This tool is used to generate CORDIC constants
 * @version 0.1
 * @date 2023-03-17
 *
 * @copyright Copyright (c) 2023
 *
 */

#include <stdint.h>

#include <stdio.h>
#include <math.h>

#define PI 3.1415926535897932384626433832795l
const double pf_off = 65536;

#define depth 16
int main()
{
    int i = 0;

    double gain = 1.0;

    // fprintf(stderr, "  2^-i     angle     factor     gain\n");
    for (int i = 0; i < depth; i++)
    {
        double di = pow(2.0, -i);
        double angle = atan(di) / PI * 180;

        double scaling_factor = sqrt(1 + di * di);

        gain *= scaling_factor;

        // fprintf(stderr, "%02.6f  %02.6f  %02.6f  %02.6f\n", di, angle, scaling_factor, gain);
    }

    gain = 1.0;

    uint32_t cordic_value[depth];
    uint32_t cordic_angle[depth];
    uint32_t cordic_gain[depth];

    for (int i = 0; i < depth; i++)
    {
        double di = pow(2.0, -i);
        double angle = atan(di);

        double scaling_factor = sqrt(1 + di * di);

        gain *= scaling_factor;

        uint32_t di_fp = di * pf_off;
        uint32_t angle_fp = angle * pf_off;
        uint32_t sf_fp = scaling_factor * pf_off;
        uint32_t ga_fp = (1.0 / gain) * pf_off;

        cordic_value[i] = di_fp;
        cordic_angle[i] = angle_fp;
        cordic_gain[i] = ga_fp;
    }
    printf(
        "/***************************************************************\n"
        " * This file is generated by tools/cordic.c, do not modify it.  \n"
        " * If you do need to change it, please modify cordic.c and      \n"
        " * run `make` to re-generate it.                                \n"
        " ***************************************************************/\n"
        "#include <libe15-fpa.h>\n"
        "\n"
        "static const fixed_t cordic_angle[] = {\n");

    for (int i = 0; i < depth; i++)
        printf("    (fixed_t){0x%08Xu},\n", cordic_angle[i]);

    printf("};\n\n");


    printf(
        "static const fixed_t cordic_gain[] = {\n");

    for (int i = 0; i < depth; i++)
        printf("    (fixed_t){0x%08Xu},\n", cordic_gain[i]);

    printf("};\n\n");
}